function out = InitializePiezoDrivers(PiezoDriverDescriptorList, GuiFigureHandle)

for ii = 1:length(PiezoDriverDescriptorList)
    PiezoDriverDescriptorList{ii}.DriverActiveXControl = 0;
    
    % initialize piezo driver
    if(PiezoDriverDescriptorList{ii}.PiezoDriverSerialNumber ~= 0)
        PiezoDriverDescriptorList{ii}.DriverActiveXControl = ...
            actxcontrol( ...
                'MGPIEZO.MGPiezoCtrl.1', ...
                PiezoDriverDescriptorList{ii}.PiezoDriverRectangle, ...
                GuiFigureHandle);
        set( ...
            PiezoDriverDescriptorList{ii}.DriverActiveXControl, ...
            'HWSerialNum', ...
            PiezoDriverDescriptorList{ii}.PiezoDriverSerialNumber);
        invoke(PiezoDriverDescriptorList{ii}.DriverActiveXControl, 'StartCtrl');
        invoke(PiezoDriverDescriptorList{ii}.DriverActiveXControl, 'SetControlMode', 0, 1);
        invoke(PiezoDriverDescriptorList{ii}.DriverActiveXControl, 'SetVoltOutput', 0, 0);
    end
    
    % initiates strain gauge reader
    if(PiezoDriverDescriptorList{ii}.StrainGaugeReaderSerialNumber ~= 0)
        PiezoDriverDescriptorList{ii}.ReaderActiveXControl = ...
            actxcontrol( ...
                'MGPIEZO.MGPiezoCtrl.1', ...
                PiezoDriverDescriptorList{ii}.StrainGaugeReaderRectangle, ...
                GuiFigureHandle);
        set( ...
            PiezoDriverDescriptorList{ii}.ReaderActiveXControl, ...
            'HWSerialNum', ...
            PiezoDriverDescriptorList{ii}.StrainGaugeReaderSerialNumber);
        invoke(PiezoDriverDescriptorList{ii}.ReaderActiveXControl, 'StartCtrl');
        invoke(PiezoDriverDescriptorList{ii}.DriverActiveXControl, 'SetControlMode', 0, 2);
        invoke(PiezoDriverDescriptorList{ii}.DriverActiveXControl, 'SetPosOutput', 0, 0);
        invoke(PiezoDriverDescriptorList{ii}.ReaderActiveXControl, 'ZeroPosition', 0);
    end

end

out = PiezoDriverDescriptorList;