function out = InitializeQpdDriver(QpdDriverDescriptor, GuiFigureHandle)

QpdDriverDescriptor.ActiveXControl = actxcontrol( ...
    'APTQUAD.APTQuadCtrl.1', ...
    QpdDriverDescriptor.Rectangle, ...
    GuiFigureHandle);
set( ...
    QpdDriverDescriptor.ActiveXControl, ...
    'HWSerialNum', ...
    QpdDriverDescriptor.SerialNumber);
invoke(QpdDriverDescriptor.ActiveXControl,'StartCtrl');
invoke(QpdDriverDescriptor.ActiveXControl,'SetQuadMode',1);

out = QpdDriverDescriptor;